# Generated by Django 3.2 on 2022-09-19 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrifying', '0002_communitypeople_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datefield',
            name='userinput',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='excercise',
            name='currentdate',
            field=models.DateField(default=datetime.date(2022, 9, 19)),
        ),
        migrations.AlterField(
            model_name='health',
            name='currentdate',
            field=models.DateField(default=datetime.date(2022, 9, 19)),
        ),
    ]
