# Generated by Django 3.2 on 2022-09-19 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrifying', '0003_auto_20220919_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datefield',
            name='userinput',
            field=models.DateField(default=datetime.date(2022, 9, 19)),
        ),
    ]
