# Generated by Django 3.2 on 2022-09-19 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrifying', '0008_auto_20220920_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypeople',
            name='timestamp',
            field=models.DateField(default=datetime.date(2022, 9, 20)),
        ),
    ]
