# Generated by Django 3.2 on 2022-09-19 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrifying', '0009_alter_communitypeople_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnedcalories',
            name='time_maintained',
            field=models.DateField(default=datetime.date(2022, 9, 20)),
        ),
    ]
