# Generated by Django 3.2 on 2022-09-19 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nutrifying', '0010_alter_earnedcalories_time_maintained'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
