# Generated by Django 3.2 on 2022-09-19 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrifying', '0011_health_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='timestamp',
            field=models.DateField(default=datetime.date(2022, 9, 20)),
        ),
    ]
