# Generated by Django 3.2 on 2022-09-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrifying', '0012_alter_health_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
