# Generated by Django 3.2 on 2022-09-20 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrifying', '0013_alter_health_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EarnedCalories',
        ),
    ]
